[versions]
agp = "9.0.0"
lifecycleLivedataCore = "2.10.0"

[libraries]
androidx-lifecycle-livedata-core = { group = "androidx.lifecycle", name = "lifecycle-livedata-core", version.ref = "lifecycleLivedataCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

